### ISSUE TITLE
Failing on Glyphicons because of -moz-osx-font-smoothing (I think)

### ISSUE THREAD

**Issue by borisschapira** [SlexAxton/css-colorguard#3]
Hi,

The script is failing on this. You can found this line of code in Glyphicon, a depandency of Twitter Bootstrap :

``` css
.glyphicon {
    -moz-osx-font-smoothing:grayscale;
}
```

Error : 

``` bash
Error : property missing ':' near line 2:37
```
